import { Router } from "express";
import {
  acceptOrder,
  completeOrder,
  confirmFuelDelivered,
  createOrder,
  customerConfirmPayment,
  getMyActiveOrder,
  getOrderHistory,
  getOrderDetails,
  listOpenOrders,
  markArrived,
  markFuelDelivered,
  providerConfirmPayment,
  raiseTowingSos,
  respondToExtraWorkRequest,
  startOrderProgress,
